version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Sanjay@2004
      - DB_NAME=employeeDb
    depends_on:
      - db

  
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Sanjay@2004
      MYSQL_DATABASE: employeeDb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
